# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='data',
            new_name='date',
        ),
    ]
